services:
  backend:
    image: hughie007/valentique-backend:latest
    container_name: valentique-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - backend-uploads:/app/uploads

  frontend:
    image: hughie007/valentique-frontend:latest
    container_name: valentique-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  backend-uploads:
